dist: trusty
sudo: required
language: node_js
node_js:
  - '8'
services:
  - mysql
install:
  - npm i
before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'CREATE DATABASE `watch-articles` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci' -uroot
  - mysql -e 'grant all privileges on `watch-articles`.* to travis@localhost' -uroot
script:
  - npm run build:front
  - npm run cov:backend
after_script:
  - npm i codecov -g && codecov
