dist: trusty
sudo: required
language: node_js
node_js:
  - '8'
services:
  - mysql
install:
  - npm i
before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql --version
script:
  - npm run build:front
  - npm run cov:backend
after_script:
  - npm i codecov -g && codecov
