dist: trusty
sudo: required
language: node_js
node_js:
  - '8'
services:
  - mysql
before_install:
  - bash .travis.install-mysql-5.7.sh
install:
  - npm i
script:
  - npm run build:front
  - npm run cov:backend
after_script:
  - npm i codecov -g && codecov
