sudo: false
language: node_js
node_js:
  - '8'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE `watch-articles` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
install:
  - npm i
script:
  - npm run build:front
  - npm run cov:backend
after_script:
  - npm i codecov -g && codecov
